routes:
  /:
    as: todo
    uses: index

  getAll:
    as: todo.getAll
    uses: getTodos

  put@complete:
    as: todo.complete
    uses: markCompleted

  post@add:
    as: todo.postAdd
    uses: postAdd

  delete@delete:
    as: todo.delete
    uses: deleteTodo
